#!/bin/bash
set -ex
DEVICE_ARCH=$(uname -m)
VERSION="${TAG}"
mkdir -p /urbit/binary
cd /urbit/binary/
if [[ $DEVICE_ARCH == "aarch64" ]]; then
  curl -L https://github.com/urbit/vere/releases/download/vere-$VERSION/linux-aarch64.tgz | tar xzk
  chmod +x /urbit/binary/vere-${VERSION}-linux-aarch64
  mv /urbit/binary/vere-${VERSION}-linux-aarch64 /usr/sbin/vere
elif [[ $DEVICE_ARCH == "x86_64" ]]; then
  curl -L https://github.com/urbit/vere/releases/download/vere-$VERSION/linux-x86_64.tgz | tar xzk
  chmod +x /urbit/binary/vere-${VERSION}-linux-x86_64
  mv /urbit/binary/vere-${VERSION}-linux-x86_64 /usr/sbin/vere
fi
ln -s /usr/sbin/vere /usr/sbin/urbit
